name: PublishSite
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        
      - name: publish
        run: |
          npm install
          npm run build
          cd dist
          printf 'afters.codecrafters.mx' > CNAME | tr -d '\n\r'
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://github.com/code-crafters/afters.codecratfters.mx.git master:gh-pages 
